openapi: 3.0.0
info:
title: ToDo API
version: 1.0.0
servers:
- url: http://localhost/todo-app/public
paths:
/api/todos:
get:
summary: Lista todos
responses:
'200': { description: OK }
post:
summary: Crear todo
requestBody:
content:
application/json:
schema:
type: object
properties:
title: { type: string }
responses:
'201': { description: Created }
/api/todos/{id}:
put:
summary: Actualizar todo
parameters:
- in: path
name: id
required: true
schema: { type: integer }
delete:
summary: Eliminar todo
/api/todos/{id}/toggle:
patch:
summary: Alternar estado de completado
parameters:
- in: path
name: id
required: true
schema: { type: integer }
responses:
'200': { description: OK }
components: {}
schemas: {}
securitySchemes: {} 